# Generated by Django 3.0.5 on 2020-04-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classroom_number', models.IntegerField(primary_key=True, serialize=False)),
                ('etage', models.IntegerField(choices=[(-1, '1. basement'), (0, 'ground level'), (1, '1. floor'), (2, '2. floor')])),
                ('constructionphase', models.IntegerField(choices=[(1, 'First Constructionphase'), (2, 'Second Constructionphase')])),
            ],
            options={
                'verbose_name': 'classroom',
                'verbose_name_plural': 'classrooms',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('ComputerID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('serialnumber', models.CharField(blank=True, max_length=256, null=True)),
                ('brand', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date_of_purchase', models.DateTimeField(blank=True, null=True)),
                ('warranty_period', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('working', 'working'), ('broken', 'broken')], max_length=7, null=True)),
                ('Class', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory_managementsentials.Class')),
            ],
            options={
                'verbose_name': 'Computer',
                'verbose_name_plural': 'Computers',
            },
        ),
        migrations.CreateModel(
            name='SpeakerSet',
            fields=[
                ('SpeakerSetID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date_of_purchase', models.DateTimeField()),
                ('warranty_period', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('working', 'working'), ('broken', 'broken')], max_length=30, null=True)),
                ('Class', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory_managementsentials.Class')),
            ],
            options={
                'verbose_name': 'SpeakerSet',
                'verbose_name_plural': 'SpeakerSets',
            },
        ),
        migrations.CreateModel(
            name='SmartBoard',
            fields=[
                ('SmartBoardID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('serialnumber', models.CharField(blank=True, max_length=256, null=True)),
                ('brand', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date_of_purchase', models.DateTimeField(blank=True, null=True)),
                ('warranty_period', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('working', 'working'), ('broken', 'broken')], max_length=7, null=True)),
                ('Class', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory_managementsentials.Class')),
            ],
            options={
                'verbose_name': 'SmartBoard',
                'verbose_name_plural': 'SmartsBoards',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('ScreenID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('serialnumber', models.CharField(blank=True, max_length=256, null=True)),
                ('brand', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date_of_purchase', models.DateTimeField(blank=True, null=True)),
                ('warranty_period', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('working', 'working'), ('broken', 'broken')], max_length=7, null=True)),
                ('Computer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory_managementsentials.Computer')),
            ],
            options={
                'verbose_name': 'Screen',
                'verbose_name_plural': 'Screens',
            },
        ),
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('CanvasID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('serialnumber', models.CharField(blank=True, max_length=256, null=True)),
                ('brand', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date_of_purchase', models.DateTimeField(blank=True, null=True)),
                ('warranty_period', models.IntegerField(blank=True, default=2, null=True)),
                ('status', models.CharField(blank=True, choices=[('working', 'working'), ('broken', 'broken')], max_length=30, null=True)),
                ('Class', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory_managementsentials.Class')),
            ],
            options={
                'verbose_name': 'CanvasBoard',
                'verbose_name_plural': 'CanvasBoards',
            },
        ),
        migrations.CreateModel(
            name='Beamer',
            fields=[
                ('BeamerID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('serialnumber', models.CharField(blank=True, max_length=256, null=True)),
                ('brand', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date_of_purchase', models.DateTimeField(blank=True, null=True)),
                ('warranty_period', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('working', 'working'), ('broken', 'broken')], max_length=7, null=True)),
                ('Class', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory_managementsentials.Class')),
            ],
            options={
                'verbose_name': 'Beamer',
                'verbose_name_plural': 'Beamers',
            },
        ),
    ]
