# Generated by Django 3.0.5 on 2020-05-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, null=True)),
                ('serialnumber', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date_of_purchase', models.DateTimeField(blank=True, null=True)),
                ('warranty_period', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('working', 'working'), ('broken', 'broken')], max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Computer',
                'verbose_name_plural': 'Computers',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[('BA', 'Keller'), ('GF', 'Erdgeschoss'), ('FF', '1. Etage'), ('SF', '2. Etage')], default='FF', max_length=2)),
                ('building', models.CharField(choices=[('BUILDING1', 'Erster Bauabschnitt'), ('BUILDING2', 'Zweiter Bauabschnitt'), ('GYMNASIUM', 'Sporthalle')], default=('BA1',), max_length=9)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory_managementsentials.Location')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='SpeakerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date_of_purchase', models.DateTimeField()),
                ('warranty_period', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('working', 'working'), ('broken', 'broken')], max_length=30, null=True)),
                ('Class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_managementsentials.Room')),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_managementsentials.Brand')),
            ],
            options={
                'verbose_name': 'SpeakerSet',
                'verbose_name_plural': 'SpeakerSets',
            },
        ),
        migrations.CreateModel(
            name='SmartBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, null=True)),
                ('serialnumber', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date_of_purchase', models.DateTimeField(blank=True, null=True)),
                ('warranty_period', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('working', 'working'), ('broken', 'broken')], max_length=7, null=True)),
                ('Class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_managementsentials.Room')),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_managementsentials.Brand')),
            ],
            options={
                'verbose_name': 'SmartBoard',
                'verbose_name_plural': 'SmartsBoards',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, null=True)),
                ('serialnumber', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date_of_purchase', models.DateTimeField(blank=True, null=True)),
                ('warranty_period', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('working', 'working'), ('broken', 'broken')], max_length=7, null=True)),
                ('Computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_managementsentials.Computer')),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_managementsentials.Brand')),
            ],
            options={
                'verbose_name': 'Screen',
                'verbose_name_plural': 'Screens',
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_managementsentials.Room'),
        ),
        migrations.AddField(
            model_name='computer',
            name='brand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_managementsentials.Brand'),
        ),
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, null=True)),
                ('serialnumber', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date_of_purchase', models.DateTimeField(blank=True, null=True)),
                ('warranty_period', models.IntegerField(blank=True, default=2, null=True)),
                ('status', models.CharField(blank=True, choices=[('working', 'working'), ('broken', 'broken')], max_length=30, null=True)),
                ('Class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_managementsentials.Room')),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_managementsentials.Brand')),
            ],
            options={
                'verbose_name': 'Canvas',
                'verbose_name_plural': 'Canvas',
            },
        ),
        migrations.CreateModel(
            name='Beamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('serialnumber', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date_of_purchase', models.DateTimeField(blank=True, null=True)),
                ('warranty_period', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('working', 'working'), ('broken', 'broken')], max_length=7, null=True)),
                ('Class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_managementsentials.Room')),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_managementsentials.Brand')),
            ],
            options={
                'verbose_name': 'Beamer',
                'verbose_name_plural': 'Beamers',
            },
        ),
    ]
