# Generated by Django 3.0.5 on 2020-04-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etage', models.IntegerField(default=50)),
                ('room_number', models.IntegerField(default=200)),
            ],
        ),
    ]
