# Generated by Django 3.0.5 on 2020-06-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='format',
            field=models.CharField(blank=True, choices=[('1:1', '1:1'), ('4:3', '4:3'), ('16:9', '16:9'), ('16:10', '16:10'), ('21:9', '21:9')], max_length=5, null=True),
        ),
    ]
