# Generated by Django 3.0.5 on 2020-06-07 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='Class',
            new_name='room',
        ),
        migrations.RemoveField(
            model_name='beamer',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='canvas',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='Computer',
        ),
        migrations.RemoveField(
            model_name='smartboard',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='speakerset',
            name='Class',
        ),
        migrations.AddField(
            model_name='room',
            name='beamer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_managementsentials.Beamer'),
        ),
        migrations.AddField(
            model_name='room',
            name='canvas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_managementsentials.Canvas'),
        ),
        migrations.AddField(
            model_name='room',
            name='chair',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='smartboard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_managementsentials.SmartBoard'),
        ),
        migrations.AddField(
            model_name='room',
            name='speakerset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_managementsentials.SpeakerSet'),
        ),
        migrations.AddField(
            model_name='room',
            name='table',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_managementsentials.Room'),
        ),
        migrations.AlterField(
            model_name='beamer',
            name='description',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='description',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='description',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_managementsentials.Location'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='description',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='smartboard',
            name='description',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='speakerset',
            name='description',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, unique=True),
        ),
    ]
