# Generated by Django 3.0.3 on 2020-06-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0002_auto_20200607_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='blackboard',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
