# Generated by Django 3.0.5 on 2020-04-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0002_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='room_number',
        ),
        migrations.AddField(
            model_name='class',
            name='class_name',
            field=models.CharField(default='DQI18', max_length=30),
        ),
        migrations.AddField(
            model_name='class',
            name='class_number',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='class',
            name='constructionphase',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='class',
            name='etage',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
