# Generated by Django 3.0.5 on 2020-06-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0002_auto_20200610_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamer',
            name='description',
            field=models.CharField(max_length=99, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='beamer',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.CharField(max_length=99, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='description',
            field=models.CharField(max_length=99, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='description',
            field=models.CharField(max_length=99, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=99, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='description',
            field=models.CharField(max_length=99, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='smartboard',
            name='description',
            field=models.CharField(max_length=99, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='smartboard',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='speakerset',
            name='description',
            field=models.CharField(max_length=99, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='speakerset',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
