# Generated by Django 3.0.5 on 2020-04-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0003_auto_20200421_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='etage',
            field=models.CharField(choices=[(1, 'ERST ETAGE'), (2, 'ZWEITE ETAGE'), (3, 'DRITEE ETAGE')], max_length=4),
        ),
    ]
