# Generated by Django 3.0.5 on 2020-04-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0004_auto_20200421_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='etage',
            field=models.CharField(choices=[(0, 'Erstes Untergeschoss'), (1, 'Erdgeschoss'), (2, '1. Etage'), (3, '2. Etage')], max_length=4),
        ),
    ]
