# Generated by Django 3.0.5 on 2020-04-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0005_auto_20200421_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_name',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_number',
            field=models.CharField(choices=[(0, 0), (1, 1)], max_length=1000),
        ),
        migrations.AlterField(
            model_name='class',
            name='etage',
            field=models.CharField(choices=[(-1, '1. Untergeschoss'), (0, 'Erdgeschoss'), (1, '1. Etage'), (2, '2. Etage')], max_length=4),
        ),
    ]
