# Generated by Django 3.0.5 on 2020-04-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0006_auto_20200421_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_number',
        ),
        migrations.AddField(
            model_name='class',
            name='class_room_nr',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='class',
            name='constructionphase',
            field=models.CharField(choices=[(1, 'Erster Bauabschnitt'), (2, 'Zweiterbauabschnitt')], max_length=2),
        ),
    ]
