# Generated by Django 3.0.5 on 2020-04-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0007_auto_20200421_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='constructionphase',
            field=models.CharField(choices=[(1, 'Erster Bauabschnitt'), (2, 'Zweiterbauabschnitt')], max_length=30),
        ),
        migrations.AlterField(
            model_name='class',
            name='etage',
            field=models.CharField(choices=[(-1, '1. Untergeschoss'), (0, 'Erdgeschoss'), (1, '1. Etage'), (2, '2. Etage')], max_length=30),
        ),
    ]
