# Generated by Django 3.0.5 on 2020-04-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0008_auto_20200421_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='moin',
            field=models.CharField(default='moin', max_length=30),
        ),
        migrations.AddField(
            model_name='class',
            name='test',
            field=models.CharField(choices=[('a', 'Erster Bauabschnitt'), ('2', 'Zweiterbauabschnitt')], default='a', max_length=30),
        ),
    ]
