# Generated by Django 3.0.5 on 2020-04-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0009_auto_20200421_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='moin',
        ),
        migrations.RemoveField(
            model_name='class',
            name='test',
        ),
        migrations.AlterField(
            model_name='class',
            name='constructionphase',
            field=models.IntegerField(choices=[(1, 'Erster Bauabschnitt'), (2, 'Zweiterbauabschnitt')]),
        ),
    ]
