# Generated by Django 3.0.5 on 2020-04-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0011_auto_20200421_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date_of_purchase', models.DateTimeField()),
                ('serialnumber', models.IntegerField()),
                ('warranty_period', models.IntegerField()),
                ('status', models.CharField(choices=[(1, 'funktioniert'), (2, 'kaputt')], max_length=30)),
            ],
        ),
    ]
