# Generated by Django 3.0.5 on 2020-04-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0012_beamer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='constructionphase',
            field=models.IntegerField(choices=[(1, 'Erster Bauabschnitt'), (2, 'Zweiter Bauabschnitt')]),
        ),
    ]
