# Generated by Django 3.0.5 on 2020-04-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0013_auto_20200421_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_room_nr',
        ),
        migrations.AddField(
            model_name='class',
            name='chairs',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='class',
            name='classroom_nr',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='class',
            name='table',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='beamer',
            name='serialnumber',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='beamer',
            name='status',
            field=models.CharField(choices=[('working', 'funktioniert'), ('broken', 'kaputt')], max_length=30),
        ),
        migrations.AlterField(
            model_name='beamer',
            name='warranty_period',
            field=models.IntegerField(default=None),
        ),
    ]
