# Generated by Django 3.0.5 on 2020-04-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0014_auto_20200421_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamer',
            name='serialnumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beamer',
            name='warranty_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class',
            name='chairs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class',
            name='classroom_nr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class',
            name='table',
            field=models.IntegerField(default=0),
        ),
    ]
