# Generated by Django 3.0.5 on 2020-04-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0016_auto_20200421_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='classroom_nr',
            new_name='classroom_ID',
        ),
    ]
