# Generated by Django 3.0.5 on 2020-04-21 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0017_auto_20200421_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamer',
            name='Class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory_managementsentials.Class'),
        ),
    ]
