# Generated by Django 3.0.5 on 2020-04-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_managementsentials', '0018_beamer_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beamer',
            options={'verbose_name': 'Beamer', 'verbose_name_plural': 'Beamer'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Klasseraum', 'verbose_name_plural': 'Klassenräume'},
        ),
    ]
